[install.scopes]
"@jsr" = "https://npm.jsr.io"

[run]
# equivalent to `bun --bun` for all `bun run` commands
# bun = true
# temporarily disabled because of "setFlagsFromString is not yet implemented in bun" when running sst
